version: '3.8'

services:
  # Только WordPress без базы данных
  wordpress:
    image: wordpress:6.4-apache
    container_name: weyer_wordpress
    restart: always
    environment:
      # Отключаем подключение к базе данных
      WORDPRESS_DB_HOST: ""
      WORDPRESS_DEBUG: 1
      WORDPRESS_DEBUG_LOG: 1
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html
      - ./weyer-theme:/var/www/html/wp-content/themes/weyer-theme
      - ./uploads:/var/www/html/wp-content/uploads
      - ./wp-config-no-db.php:/var/www/html/wp-config.php
      # Подключаем наши статические файлы
      - ./static-site:/var/www/html/static-site
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/static-site/"]
      timeout: 10s
      retries: 5

  # Простой PHP сервер для демонстрации
  php-demo:
    image: php:8.2-apache
    container_name: weyer_php_demo
    restart: always
    ports:
      - "8090:80"
    volumes:
      - ./demo-site:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html

volumes:
  wordpress_data: